### ISSUE TITLE
Collision layer does not work

### ISSUE THREAD

**Issue by CharlesQHappy** [svenberra/NewtonUnityPlugin#13]
no matter how i set the collider's layer, they always collide with each other......

**Comment by svenberra** [comment]
Hmm, don't remember exactly how that was setup.
I think to disable collision between two bodies you need to disable collision on the physics material pair(NewtonMaterialInteraction class) instead.
That is, define one material for body a and one for body b. Then define what happens when these two materials collide.
Check the folder Demos\Assets\Resources\Newton Materials\ for example materials.
Raycasting make use of the layer system in Unity though(Demo 23).

**Comment by CharlesQHappy** [comment]
i have tried, but noting changed...

**Comment by svenberra** [comment]
Hmm, seems collision enabling/disabling wasn't fully finished.
Check the file dNewtonWorld.cpp in NewtonWrapper/wrappersdk, line 365.
Uncomment this and see if that works
`//return materialProp.m_collisionEnable ? 1 : 0;`
