### ISSUE TITLE
Can i use my own collision detection algorithm？

### ISSUE THREAD

**Issue by CharlesQHappy** [svenberra/NewtonUnityPlugin#15]
Can i use my own collision detection algorithm, then send the result to newton's contact response method?

**Comment by JulioJerez** [comment]
you can, although I'd never use a diffrent routine to calculate contacts.
the simples way without changing the engine is by replacing the narrow phase call to calcuat the contact points, by setting your own call back.
I use this is some demos like the excavator demo, wher ethe thread are so thing that if using the 
box polygon collision they would be penetration the grown all the time, pluse will generate many extra extra contacts a the edge when tow link meet that will make the system matrixs ill conditined and expensive to solve.  Instead each link is a compound that uses link collsion shape for each dynamics collsions but uses an offset sphere located at the center of the link, to generate only one contact per link with static bodies. the code set in up, and you can look at the demo for the function callback implementation of ThreadStaticContactsGeneration. 
> 		NewtonMaterialSetCallbackUserData(world, threadMaterialID, threadMaterialID, this);
> 		NewtonMaterialSetCollisionCallback (world, threadMaterialID, threadMaterialID, StandardAABBOverlapTest, NULL);
> 		NewtonMaterialSetContactGenerationCallback (world, threadMaterialID, threadMaterialID, ThreadStaticContactsGeneration);
>  

This is a funtionality that is advanced, and I do not recommend, the collsion system in newton is quiet robust, fast an acurate. plus you need to remember hwo the shape definitions which is not exposed to the user interface, but yes this is very possible.  

the secund part will require you to alter the dgWord class to allow for registering a broadphase class, 
there are two implemented inside the engine, and maybe some day they will be another for GPU. 
but this you are on your own.  
the class is called dgBroadPhase and if you subclass from it and implement all the abstract functions
you can replace the broad phase, again this is not as eassy as you think. There are 15 year of development on that collision system. 

no sure what you are doing that you need to replace the collision, but before you do that maybe study the how they are implement in the engine. it is quite robust and numerically stable. 
Numerically stable is a very important aspect of the problem and is the feature lack but the large majority of collision algorithm that I'd seem.

**Comment by CharlesQHappy** [comment]
1、Can i do that all in this unity  plugin or do i have to modify the c++ source code?
2、Here is my situation: I need to do collision detection between a rigid object and an animatated object(deform aniamtion) ,and the unity plugin now did not support this collision detction.

**Comment by CharlesQHappy** [comment]
By the way, i have to use newton physics  within unity engine.

**Comment by JulioJerez** [comment]
oh, this is Unity. 
Setting low level callback to inteface with managed laguage has provent to be a very difficult task.
The plugin for Unity offer a very limited set of the engine functionality, for that reason.  
Basically you can no set delegate function that you can call thousand of time in a single Physics update, which is what happens on those callback, on top of that Unity does no allows for assessing unity component or Game Objects from a cpp delegate, instead we has to set up on data structure and copy everything once at the beggining of the update and retrieve the results after the update. and even that small numberr of calls is enough to make the plug in very inefficient compared to Unity implementation of the physics enguine they use which is Native and has some advantage over other.

Are you describing a deformable mesh collision? or some kind of bone base animated body?
for a bone base, would an approximated rag doll do the trick?
for a deformable there is a user define collsion mesh that only apply to static bodies, but I have to tell you that once you start deforming a righ body, the physics of a rigid body is very different than the physics of deformable bodies. this is not just a collision problem.    

you said you has to use Newton, I never heard anybody saying that. There is nothing that I know about that makes a anyone obligated to use the Newton Plugin.  

In all honesty, what you are describing in beyond of what a rigid body simulator can offer, the amount of modifications are so vast and drastic that we are talking of a technology other than rigid body approximation of mechanical system.
Newton is not prepared to address this problem now, maybe some day when we finally address the deformably body problem.

But there are libraries that do adress these kind of problem you are describing.
AMD just released a practical and real time class one that you may have better luck 
trying, instead of engaging on such large changes to the newton engine on such weak promise. 
https://github.com/GPUOpen-Effects/FEMFX

**Comment by CharlesQHappy** [comment]
Thanks for the detailed reply! I need to clarify that the collision is actually between two rigid objects both consists of triangles . One is convex and the other is concave. The concave one is deformed periodically  and I know how it deforms when given any specific time. So the concave one can be seemed as rigid body indeed.  The unity plugin has all that i need as long as it can support what i describe above. Maybe a little change can implement that :), cause it is not a real softbody collision detection. Can you please help me?

**Comment by CharlesQHappy** [comment]
The newton physics can implement some effects which finite element method can do at least in my project! Any other like bullet physics, unity's self physics engine can not.

**Comment by JulioJerez** [comment]
I thank for the appreciation, but I do not want to mislead you, teh Newton engine does not do finite element analysis. 
we has some experimentation for Tetrahedral deformable bodies base of stiff spring that for terat volumes, but that work is on hold for now.
My plan is to resume thet work for 2020, but this is a work in progress.
