### ISSUE TITLE
Building Problems

### ISSUE THREAD

**Issue by CharlesQHappy** [svenberra/NewtonUnityPlugin#19]
When i open the NewtonUnityPlugin.sln, the files generated by swig is missing, how's that?
![error1](https://user-images.githubusercontent.com/54677365/74083745-8bde9900-4aa2-11ea-887b-cc834239d324.png)
![error2](https://user-images.githubusercontent.com/54677365/74083747-8d0fc600-4aa2-11ea-9604-40c5c3d184ea.png)

**Comment by CharlesQHappy** [comment]
I have been trying to use SWIG to rebuild the "newton.i" file, but i encounter an syntax error:
![图片](https://user-images.githubusercontent.com/54677365/74083622-5dac8980-4aa1-11ea-9779-0d042b4040c7.png)
and the corresponding code is : 
![未命名1581158231](https://user-images.githubusercontent.com/54677365/74083689-0fe45100-4aa2-11ea-850b-bb2d0246e4b3.png)
I can not see why the error occured, please help me around.

**Comment by svenberra** [comment]
Newton_wrap.cxx is generated by swig when building the solution. If swig fails the file won't exist. Why swig fail i don't know. Most likely due to alot of changes in Newton. Unfortunately i haven't had much time to update the plugin lately so for now try to revert to an older version of Newton. Closer to the latest update of this plugin.

**Comment by CharlesQHappy** [comment]
Thanks for your reply!  It indeed dues to the wrong Newton Dynamics version. I convert to use version of date 2019.6.30, it works!
